python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=hessian_contour
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=hessian_contour_model_information
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=ttk_merge_tree
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=loss_landscapes_contour
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=model_weight_similarity
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=layer_euclidean_distance_similarity
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=model_euclidean_distance_similarity
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=cka_model_similarity
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=hessian_loss_landscape
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=loss_landscapes_contour_3d
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=loss_landscapes_global
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=global_structure
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=ttk_persistant_diagram
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=loss_landscapes_detailed_similarity
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=model_analysis_information
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=prediction_distribution
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=prediction_distribution_labels
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=training_loss_landscape
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=layer_cka_similarity
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=loss_landscapes_contour_3d_training
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=layer_cka_similarity
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=layer_torch_cka_similarity
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=ttk_merge_tree_training
python3 drop_collection.py --client=mongodb07.nersc.gov --database=losslensdb --collection=ttk_persistant_diagram_training